### ISSUE TITLE
Length error for compressed instructions (RVC_NAND+RVC_NANDI)

### ISSUE THREAD

**Issue by thomasgoodfellow** [tum-ei-eda/seal5#126]
Running rvc_demo.py from the develop branch fails:

    INFO - [2024-10-24 14:18:49]::INFO - loading models
    INFO - ERROR - /space/thomasg/tum12/seal5_llvm_rvcdemo_1024/.seal5/temp/ExampleRV32C/XRVC/XRVC_NAND.core_desc:8: instruction length is not 32 bits
    INFO -
    INFO - ERROR - /space/thomasg/tum12/seal5_llvm_rvcdemo_1024/.seal5/temp/ExampleRV32C/XRVC/XRVC_NANDI.core_desc:8: instruction length is not 32 bits
    INFO -
    INFO - Writing gmir for XRV_NAND.ll
    WARNING - Skipping XRVC_NAND due to errors.
    INFO - Writing gmir for XRV_NANDI.ll
    WARNING - Skipping XRVC_NANDI due to errors.

Log attached
[seal5.log](https://github.com/user-attachments/files/17506852/seal5.log)

**Comment by PhilippvK** [comment]
Fixed via 1693ff4 on #134 .

The CoreDSL2LLVM Parser does not support compressed instructions. We are not interested in generating patterns for them anyways, hence the pass should skip those instructions.
